<?hh

namespace Config;

# The following class is auto-generated by generateRouterConfig.php.
class RouteMap {

// Defines the routing mapping from the request URI to the controller.
public static ImmMap<string, string> $s_map = ImmMap {
  "/account" => "AccountController",
  "/activate_account" => "ActivateAccountController",
  "/dashboard" => "DashboardController",
  "/error" => "ErrorController",
  "/example" => "ExampleController",
  "/home" => "HomePageController",
  "/login" => "LoginController",
  "/logout" => "LogoutController",
  "/register_user" => "RegisterUserController",
  "/user_settings" => "UserSettingsController",
  "/venues" => "VenueController"
};

}
